WebApp/Pages/Benefits/Create.cshtml.cs
using Edgias.Humano.WebApp.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Edgias.Humano.WebApp.Pages.Benefits
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public string Name { get; set; } = default!;

        [BindProperty]
        public decimal EmployeeDeduction { get; set; }

        [BindProperty]
        public decimal CompanyContribution { get; set; }

        private readonly IBenefitService _benefitService;

        public CreateModel(IBenefitService benefitService)
        {
            _benefitService = benefitService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            await _benefitService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/CheckIns/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.CheckIns
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public Guid EmployeeId { get; set; }

        [BindProperty]
        public DateTime Date { get; set; } = DateTime.Now;

        [BindProperty]
        public string TimeIn { get; set; } = string.Empty;

        [BindProperty]
        public string? TimeOut { get; set; }

        private readonly ICheckInService _checkInService;

        public CreateModel(ICheckInService checkInService)
        {
            _checkInService = checkInService;
        }

        public void OnGet(Guid id)
        {
            EmployeeId = id;
        }

        public async Task<IActionResult> OnPost()
        {
            await _checkInService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Departments/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.Departments
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public string Name { get; set; } = string.Empty;

        [BindProperty]
        public string? Email { get; set; }

        private readonly IDepartmentService _departmentService;

        public CreateModel(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            await _departmentService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Employees/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using Edgias.Humano.ApplicationCore.Entities;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.Employees
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public EmployeeType EmployeeType { get; set; }

        [BindProperty]
        public string FirstName { get; set; } = string.Empty;

        [Required]
        [BindProperty]
        public string LastName { get; set; } = string.Empty;

        [BindProperty]
        public string NationalId { get; set; } = string.Empty;

        [BindProperty]
        public DateTime DateJoined { get; set; } = DateTime.Now;

        [BindProperty]
        public DateTime DateOfBirth { get; set; } = DateTime.Now;

        [BindProperty]
        public Gender Gender { get; set; }

        [BindProperty]
        public Guid DepartmentId { get; set; }

        [BindProperty]
        public Guid? ManagerId { get; set; }

        [BindProperty]
        public string? Email { get; set; }

        [BindProperty]
        public string Mobile { get; set; } = string.Empty;

        [BindProperty]
        public string Street { get; set; } = string.Empty;

        [BindProperty]
        public string City { get; set; } = string.Empty;

        [BindProperty]
        public string? State { get; set; }

        [BindProperty]
        public string? Country { get; set; } = "Zimbabwe";

        [BindProperty]
        public Guid SalutationId { get; set; }

        public SelectList? Salutations { get; set; }
        public SelectList? Departments { get; set; }
        public SelectList? Managers { get; set; }

        private readonly IDepartmentService _departmentService;
        private readonly IEmployeeService _employeeService;
        private readonly ISalutationService _salutationService;

        public CreateModel(IDepartmentService departmentService,
            IEmployeeService employeeService,
            ISalutationService salutationService)
        {
            _departmentService = departmentService;
            _employeeService = employeeService;
            _salutationService = salutationService;
        }

        public async Task OnGet()
        {
            var departments = await _departmentService.GetAll();
            var salutations = await _salutationService.GetAll();
            var employees = await _employeeService.GetAll();
            Managers = new SelectList(employees.Select(d => new { d.Id, Name = $"{d.FirstName} {d.LastName}({d.NationalId})" }), "Id", "Name");
            Salutations = new SelectList(salutations, "Id", "Name");
            Departments = new SelectList(departments, "Id", "Name");
        }

        public async Task<IActionResult> OnPost()
        {
            await _employeeService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Employees/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.Employees
{
    public class DetailsModel : PageModel
    {
        [BindProperty]
        public CheckInModalModel CheckInModalModel { get; set; } = new();

        [BindProperty]
        public LeaveModalModel LeaveModalModel { get; set; } = new(); 

        [BindProperty]
        public QualificationModalModel QualificationModalModel { get; set; } = new();

        [BindProperty]
        public TimesheetModalModel TimesheetModalModel { get; set; } = new();

        [BindProperty]
        public WorkExperienceModalModel WorkExperienceModalModel { get; set; } = new();

        public EmployeeDetailsModel Employee { get; set; } = null!;

        private readonly IEmployeeService _employeeService;
        private readonly IJobTitleService _jobTitleService;
        private readonly IGradeService _gradeService;
        private readonly ILeaveCategoryService _leaveCategoryService;
        private readonly IProjectService _projectService;

        public DetailsModel(IEmployeeService employeeService,
            IJobTitleService jobTitleService,
            IGradeService gradeService,
            ILeaveCategoryService leaveCategoryService,
            IProjectService projectService)
        {
            _employeeService = employeeService;    
            _jobTitleService = jobTitleService;
            _gradeService = gradeService;
            _leaveCategoryService = leaveCategoryService;
            _projectService = projectService;
        }

        public async Task OnGet(Guid id)
        {
            Employee = await _employeeService.GetEmployeeWithAllDetailsById(id);
            var jobTitles = await _jobTitleService.GetAll();
            var grades = await _gradeService.GetAll();
            var leaveCategories = await _leaveCategoryService.GetAll();
            var projects = await _projectService.GetAll();
            var durations = new List<string>() { "All Day", "Half Day" };

            CheckInModalModel.EmployeeId = id;
            LeaveModalModel.EmployeeId = id;
            LeaveModalModel.Durations = new SelectList(durations.Select(d => new { Id = d, Name = d }), "Id", "Name");
            QualificationModalModel.EmployeeId = id;
            TimesheetModalModel.EmployeeId = id;
            TimesheetModalModel.Projects = new SelectList(projects, "Id", "Name");
            WorkExperienceModalModel.EmployeeId = id;
            LeaveModalModel.LeaveCategories = new SelectList(leaveCategories, "Id", "Name");
            WorkExperienceModalModel.JobTitles = new SelectList(jobTitles, "Id", "Name");
            WorkExperienceModalModel.Grades = new SelectList(grades, "Id", "Name");
        }

        public async Task<IActionResult> OnPostCheckIn()
        {
            await _employeeService.AddCheckIn(CheckInModalModel);

            return RedirectToPage("./Details", new { id = CheckInModalModel.EmployeeId });
        }

        public async Task<IActionResult> OnPostLeave()
        {
            await _employeeService.AddLeave(LeaveModalModel);

            return RedirectToPage("./Details", new { id = LeaveModalModel.EmployeeId });
        }

        public async Task<IActionResult> OnPostQualification()
        {
            await _employeeService.AddQualification(QualificationModalModel);

            return RedirectToPage("./Details", new { id = QualificationModalModel.EmployeeId });
        }

        public async Task<IActionResult> OnPostTimesheet()
        {
            await _employeeService.AddTimesheet(TimesheetModalModel);

            return RedirectToPage("./Details", new { id = TimesheetModalModel.EmployeeId });
        }

        public async Task<IActionResult> OnPostWorkExperience()
        {
            await _employeeService.AddWorkExperience(WorkExperienceModalModel);

            return RedirectToPage("./Details", new { id = WorkExperienceModalModel.EmployeeId });
        }
    }
}

WebApp/Pages/Employees/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.Employees
{
    public class IndexModel : PageModel
    {
        public IEnumerable<EmployeeIndexModel> Employees { get; set; } 

        private readonly IEmployeeService _employeeService;

        public IndexModel(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
            Employees = Enumerable.Empty<EmployeeIndexModel>();
        }

        public async Task OnGetAsync()
        {
            Employees = await _employeeService.GetAll();
        }
    }
}

WebApp/Pages/Grades/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.Grades
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public string Name { get; set; } = string.Empty;

        [BindProperty]
        public decimal MinimumSalary { get; set; }

        [BindProperty]
        public decimal MaximumSalary { get; set; }

        private readonly IGradeService _gradeService;

        public CreateModel(IGradeService gradeService)
        {
            _gradeService = gradeService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            await _gradeService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/JobTitles/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.JobTitles
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public string Name { get; set; } = string.Empty;

        private readonly IJobTitleService _jobTitleService;

        public CreateModel(IJobTitleService jobTitleService)
        {
            _jobTitleService = jobTitleService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            await _jobTitleService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/LeaveCategories/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.LeaveCategories
{
    public class CreateModel : PageModel
    {
        [Required]
        [BindProperty]
        public string Name { get; set; } = string.Empty;

        [Required]
        [BindProperty]
        public int Allocation { get; set; }

        private readonly ILeaveCategoryService _leaveCategoryService;

        public CreateModel(ILeaveCategoryService leaveCategoryService)
        {
            _leaveCategoryService = leaveCategoryService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            await _leaveCategoryService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Projects/Create.cshtml.cs
using Edgias.Humano.WebApp.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Edgias.Humano.WebApp.Pages.Projects
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public string Name { get; set; } = default!;

        [BindProperty]
        public string Description { get; set; } = default!;

        [BindProperty]
        public int Duration { get; set; }

        [BindProperty]
        public DateTime StartDate { get; set; } = DateTime.Now;

        [BindProperty]
        public DateTime? EndDate { get; set; }

        private readonly IProjectService _projectService;

        public CreateModel(IProjectService projectService)
        {
            _projectService = projectService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            await _projectService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Projects/Details.cshtml.cs
using Edgias.Humano.WebApp.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Edgias.Humano.WebApp.Pages.Projects
{
    public class DetailsModel : PageModel
    {
        public ProjectDetailsModel Project { get; set; } = default!;

        private readonly IProjectService _projectService;

        public DetailsModel(IProjectService projectService)
        {
            _projectService = projectService;
        }

        public async Task OnGetAsync(Guid id)
        {
            Project = await _projectService.GetProjectDetails(id);
        }
    }
}

WebApp/Pages/Rates/Create.cshtml.cs
using Edgias.Humano.WebApp.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Edgias.Humano.WebApp.Pages.Rates
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public string Name { get; set; } = default!;

        [BindProperty]
        public decimal Amount { get; set; }

        private readonly IRateService _rateService;

        public CreateModel(IRateService rateService)
        {
            _rateService = rateService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            await _rateService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Salutations/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.Salutations
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public string Name { get; set; } = string.Empty;

        private readonly ISalutationService _salutationService;

        public CreateModel(ISalutationService salutationService)
        {
            _salutationService = salutationService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            await _salutationService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Timesheets/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Edgias.Humano.WebApp.Interfaces;

namespace Edgias.Humano.WebApp.Pages.Timesheets
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public string Description { get; set; } = default!;

        [BindProperty]
        public DateTime Date { get; set; } = DateTime.Now;

        [BindProperty]
        public int NumberOfHours { get; set; }

        [BindProperty]
        public Guid EmployeeId { get; set; }

        [BindProperty]
        public Guid? ProjectId { get; set; }

        private readonly ITimesheetService _timesheetService;

        public CreateModel(ITimesheetService timesheetService)
        {
            _timesheetService = timesheetService;
        }

        public void OnGet(Guid id)
        {
            EmployeeId = id;
        }

        public async Task<IActionResult> OnPost()
        {
            await _timesheetService.Create(this);

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Employees/_CheckInModal.cshtml
@model CheckInModalModel

<div class="modal fade" id="check-in-modal">
    <div class="modal-dialog modal-lg">
        <form method="post" asp-page-handler="CheckIn">
            @Html.HiddenFor(we => we.EmployeeId)
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Check In</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="Date" class="col-sm-2 col-form-label">Date <code>*</code></label>
                        <input type="date" class="form-control form-control-sm" asp-for="Date" placeholder="Enter date">
                    </div>
                    <div class="form-group">
                        <label asp-for="TimeIn" class="col-sm-2 col-form-label">Time In <code>*</code></label>
                        <input type="time" class="form-control form-control-sm" asp-for="TimeIn" placeholder="Enter time in">
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

WebApp/Pages/Employees/_LeaveModal.cshtml
@model LeaveModalModel

<div class="modal fade" id="leave-modal">
    <div class="modal-dialog modal-lg">
        <form method="post" asp-page-handler="Leave">
            @Html.HiddenFor(we => we.EmployeeId)
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Leave</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="LeaveCategoryId" class="col-sm-3 col-form-label">Category <code>*</code></label>
                        <select class="form-control" asp-for="LeaveCategoryId" asp-items="Model.LeaveCategories">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Duration" class="col-sm-2 col-form-label">Duration <code>*</code></label>
                        <select class="form-control" asp-for="Duration" asp-items="Model.Durations">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartDate" class="col-sm-2 col-form-label">Start Date <code>*</code></label>
                        <input type="date" class="form-control form-control-sm" asp-for="StartDate" placeholder="Enter date">
                    </div>
                    <div class="form-group">
                        <label asp-for="EndDate" class="col-sm-2 col-form-label">End Date </label>
                        <input type="date" class="form-control form-control-sm" asp-for="EndDate" placeholder="Enter date">
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

WebApp/Pages/Employees/_QualificationModal.cshtml
@model QualificationModalModel

<div class="modal fade" id="qualification-modal">
    <div class="modal-dialog modal-lg">
        <form method="post" asp-page-handler="Qualification">
            @Html.HiddenFor(we => we.EmployeeId)
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Qualification</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="School" class="col-sm-2 col-form-label">School <code>*</code></label>
                        <input type="text" class="form-control form-control-sm" asp-for="School" placeholder="Enter school name">
                    </div>
                    <div class="form-group">
                        <label asp-for="Level" class="col-sm-2 col-form-label">Qualificafication Level <code>*</code></label>
                        <select class="form-control" asp-for="Level" asp-items="Html.GetEnumSelectList<Edgias.Humano.ApplicationCore.Entities.QualificationLevel>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Grade" class="col-sm-2 col-form-label">Grade (Results) <code>*</code></label>
                        <input type="text" class="form-control form-control-sm" asp-for="Grade" placeholder="Enter results">
                    </div>
                    <div class="form-group">
                        <label asp-for="FieldOfStudy" class="col-sm-3 col-form-label">Description <code>*</code></label>
                        <textarea rows="5" class="form-control form-control-sm" asp-for="FieldOfStudy" placeholder="Enter field of study"></textarea>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartDate" class="col-sm-2 col-form-label">Start Date <code>*</code></label>
                        <input type="date" class="form-control form-control-sm" asp-for="StartDate" placeholder="Enter date">
                    </div>
                    <div class="form-group">
                        <label asp-for="EndDate" class="col-sm-2 col-form-label">End Date </label>
                        <input type="date" class="form-control form-control-sm" asp-for="EndDate" placeholder="Enter date">
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

WebApp/Pages/Employees/_TimesheetModal.cshtml
@model TimesheetModalModel

<div class="modal fade" id="timesheet-modal">
    <div class="modal-dialog modal-lg">
        <form method="post" asp-page-handler="Timesheet">
            @Html.HiddenFor(we => we.EmployeeId)
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Timesheet</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="Date" class="col-sm-2 col-form-label">Date <code>*</code></label>
                        <input type="date" class="form-control form-control-sm" asp-for="Date" placeholder="Enter date">
                    </div>
                    <div class="form-group">
                        <label asp-for="NumberOfHours" class="col-sm-3 col-form-label">Number of Hours <code>*</code></label>
                        <input type="number" class="form-control form-control-sm" asp-for="NumberOfHours" placeholder="Enter hours">
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="col-sm-3 col-form-label">Description <code>*</code></label>
                        <textarea rows="5" class="form-control form-control-sm" asp-for="Description" placeholder="Enter description"></textarea>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectId" class="col-sm-3 col-form-label">Project </label>
                        <select class="form-control" asp-for="ProjectId" asp-items="Model.Projects">
                            <option value="">Please select</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

WebApp/Pages/Employees/_WorkExperienceModal.cshtml
@model WorkExperienceModalModel

<div class="modal fade" id="work-experience-modal">
    <div class="modal-dialog modal-lg">
        <form method="post" asp-page-handler="WorkExperience">
            @Html.HiddenFor(we => we.EmployeeId)
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Work Experience</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="Salary" class="col-sm-2 col-form-label">Salary <code>*</code></label>
                        <input type="number" class="form-control form-control-sm" asp-for="Salary" placeholder="Enter salary">
                    </div>
                    <div class="form-group">
                        <label asp-for="JobTitleId" class="col-sm-3 col-form-label">Job Title <code>*</code></label>
                        <select class="form-control" asp-for="JobTitleId" asp-items="Model.JobTitles">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="GradeId" class="col-sm-3 col-form-label">Grade <code>*</code></label>
                        <select class="form-control" asp-for="GradeId" asp-items="Model.Grades">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartDate" class="col-sm-2 col-form-label">Start Date <code>*</code></label>
                        <input type="date" class="form-control form-control-sm" asp-for="StartDate" placeholder="Enter date">
                    </div>
                    <div class="form-group">
                        <label asp-for="EndDate" class="col-sm-2 col-form-label">End Date </label>
                        <input type="date" class="form-control form-control-sm" asp-for="EndDate" placeholder="Enter date">
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->